#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT
//#define PERMISSIVE_HOLD
//#define HOLD_ON_OTHER_KEY_PRESS
#define ONESHOT_TAP_TOGGLE 5
#define ONESHOT_TIMEOUT 5000
